name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_PROJECT_KEY: pjs-blog-platform_pjs-blog-platform-backend
      SONAR_HOST_URL: https://sonarcloud.io/
      SONAR_ORGANIZATION_KEY: pjs-blog-platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run SonarCloud Analysis Begin
        uses: SonarSource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test and Collect Code Coverage
        run: dotnet test --configuration Release --collect:"Code Coverage"

      - name: Publish SonarCloud Report to GitHub
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION_KEY }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
